name: Actualizar Tabla de LoL de forma Automatica

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Ejecutar scripts de actualización y estado
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      run: |
        pip install requests
        python actualizar_datos.py
        python live_status.py

    - name: Guardar cambios en GitHub
      run: |
        git config --global user.name 'RiotBot'
        git config --global user.email 'riotbot@github.com'
        git add datos.json live_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizacion automatica general y de estados" && git push)
